dist: bionic
language: node_js

matrix:
  include:
    - os: linux
      node_js: "8"
      dist: bionic
      env: OS=linux
    - os: windows
      node_js: "10"
      env: OS=windows

before_script:
- npm run lint

script:
- if [ "$OS" = "linux" ]; then npm test; fi
- if [ "$OS" = "windows" ]; then npm run test:windows; fi

notifications:
  email:
    on_success: never
