dist: bionic
language: node_js

matrix:
  include:
    - os: linux
      node_js: "8"
      dist: bionic
    - os: windows
      node_js: "10"

before_script:
- npm run lint

notifications:
  email:
    on_success: never
